// A premium invoice document mock that mirrors the real PDF engine output —
// branded header band, billed-to block, line items, tax breakdown and totals.

const ITEMS = [
  ['Website Design Package', '1', '$3,500.00', '$3,500.00'],
  ['SEO Audit & Strategy', '1', '$1,200.00', '$1,200.00'],
  ['Monthly Retainer', '2', '$2,000.00', '$4,000.00'],
];

export default function InvoiceMock({ className = '' }) {
  return (
    <div className={`mx-auto w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-popover ring-1 ring-black/5 dark:ring-white/10 ${className}`}>
      {/* Brand band */}
      <div className="flex items-start justify-between bg-gradient-to-br from-brand-600 to-accent-600 px-6 py-5 text-white">
        <div className="flex items-center gap-2.5">
          <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-white/95 text-lg font-bold text-brand-600">S</span>
          <div>
            <p className="text-sm font-bold leading-tight">Acme Studio</p>
            <p className="text-[10px] text-white/70">500 Innovation Way, Austin</p>
          </div>
        </div>
        <div className="text-right">
          <p className="text-xl font-bold tracking-tight">INVOICE</p>
          <p className="text-[11px] text-white/80">INV-2026-0015</p>
          <span className="mt-1 inline-block rounded-full bg-white/20 px-2 py-0.5 text-[9px] font-bold uppercase tracking-wide">Sent</span>
        </div>
      </div>

      {/* Meta */}
      <div className="flex justify-between px-6 py-4 text-[11px]">
        <div>
          <p className="font-semibold uppercase tracking-wide text-ink-400">Billed to</p>
          <p className="mt-1 font-semibold text-ink-800">Apex Fitness Co.</p>
          <p className="text-ink-500">billing@apexfitness.com</p>
        </div>
        <div className="text-right text-ink-500">
          <p>Issue: <span className="text-ink-700">Jun 2, 2026</span></p>
          <p>Due: <span className="text-ink-700">Jul 2, 2026</span></p>
          <p className="mt-1 text-base font-bold text-brand-600">$8,700.00</p>
        </div>
      </div>

      {/* Items */}
      <div className="px-6">
        <div className="grid grid-cols-12 rounded-md bg-brand-50 px-2 py-1.5 text-[9px] font-bold uppercase tracking-wide text-brand-600">
          <span className="col-span-6">Description</span>
          <span className="col-span-2 text-right">Qty</span>
          <span className="col-span-4 text-right">Amount</span>
        </div>
        {ITEMS.map(([d, q, , total]) => (
          <div key={d} className="grid grid-cols-12 border-b border-ink-100 px-2 py-2 text-[11px]">
            <span className="col-span-6 text-ink-700">{d}</span>
            <span className="col-span-2 text-right text-ink-500">{q}</span>
            <span className="col-span-4 text-right font-semibold text-ink-800">{total}</span>
          </div>
        ))}
      </div>

      {/* Totals */}
      <div className="px-6 py-4">
        <div className="ml-auto w-48 space-y-1 text-[11px]">
          <div className="flex justify-between text-ink-500"><span>Subtotal</span><span>$8,700.00</span></div>
          <div className="flex justify-between text-ink-500"><span>Tax (10%)</span><span>$870.00</span></div>
          <div className="mt-1 flex justify-between rounded-md bg-brand-50 px-2 py-1.5 text-sm font-bold text-ink-900"><span>Total</span><span>$9,570.00</span></div>
        </div>
      </div>
      <div className="border-t border-ink-100 px-6 py-2.5 text-center text-[9px] text-ink-400">
        Acme Studio · Thank you for your business · Generated by SmartInvoice Pro
      </div>
    </div>
  );
}
